### ISSUE TITLE
KeyError: 391090

### ISSUE THREAD

**Issue by seungjun45** [nocaps-org/updown-baseline#5]
I got this error when I run 'train with CBS':

Traceback (most recent call last):
  File "scripts/train.py", line 205, in <module>
    batch = next(train_dataloader)
  File "/mnt/server5_hard1/seungjun/nocaps/updown/utils/common.py", line 21, in cycle
    for batch in dataloader:
  File "/home/cilab7/anaconda3/envs/sj_torch1.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/cilab7/anaconda3/envs/sj_torch1.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/mnt/server5_hard1/seungjun/nocaps/updown/data/datasets.py", line 80, in __getitem__
    image_features = self._image_features_reader[image_id]
  File "/mnt/server5_hard1/seungjun/nocaps/updown/data/readers.py", line 89, in __getitem__
    index = self._map[image_id]
KeyError: 391090

In my opinion, this is due to inconsistency between "json" and "image features" at "updown/data/datasets.py" -> line 68 and line 69? :

@classmethod
    def from_config(cls, config: Config, **kwargs):
        r"""Instantiate this class directly from a :class:`~updown.config.Config`."""
        _C = config
        vocabulary = kwargs.pop("vocabulary")
        return cls(
            vocabulary=vocabulary,
            **image_features_h5path=_C.DATA.INFER_FEATURES,
            captions_jsonpath=_C.DATA.TRAIN_CAPTIONS,**
            max_caption_length=_C.DATA.MAX_CAPTION_LENGTH,
            in_memory=kwargs.pop("in_memory"),
        )

Isn't it suppose to be 
image_features_h5path=_C.DATA.TRAIN_FEATURES, ?

**Comment by GaryYufei** [comment]
Hi @seungjun45 Thanks for pointing this out. Could you make this change and open a PR? We will be happy to merge it!
